apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeassist-frontend
  namespace: kubeassist
  labels:
    app: kubeassist-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeassist-frontend
  template:
    metadata:
      labels:
        app: kubeassist-frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: docker.io/lentil1016/kubeassist-frontend:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
