apiVersion: v1
kind: Service
metadata:
  name: kubeassist-frontend
  namespace: kubeassist
spec:
  selector:
    app: kubeassist-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
